version: '3'
services:
  cwcsample-app:
    build: springcontroller
    container_name: cwcsample-controller
    ports:
      - 8080:8080

  cwcsample-ui:
    build: react
    container_name: cwcsample-ui
    ports:
      - 3000:3000
    extra_hosts:
      - "localhost:host-gateway"